### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by NIcholasfuguier** [MiracleFactory/MF-Research-Motherboard-Dataset#1]
Dear Author, Hello, the resource website connected to this dataset is not accessible in China, and cannot be downloaded, and cannot be accessed by using a VPN for proxy, can you please share another download link? Thank you!

**Comment by yuelinxin** [comment]
Hi, sorry for the late reply. The links are now fixed.

**Comment by NIcholasfuguier** [comment]
Thank you for your reply, it has been received and your work has given a boost to my research, thank you again!


Nicholas&nbsp;Fuguier~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miraclefactory/motherboard-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 晚上11:14
***@***.***&gt;;
抄送:&nbsp;"Nicholas ***@***.******@***.***&gt;;
主题:&nbsp;Re: [miraclefactory/motherboard-dataset] Unable to download dataset (Issue #1)





 
Hi, sorry for the late reply. The links are now fixed.
